function [Sys, Exp, Opt] = default_easyspin_parameters_triplet(x_values)

Sys = struct(...
    'S', 1, ...
    'g', 2.0023, ...
    'D', [1200 100], ...
    'lw', [2, 2] ...
    );
Exp = struct(...
    'Range', [min(x_values), max(x_values)], ...
    'nPoints', length(x_values), ...
    'mwFreq', 9.67, ...
    'Harmonic', 0, ...
    'Temperature', [0.2, 0.3, 0.5] ...
    );
Opt = struct();

end