function [Sys, Exp, Opt] = default_easyspin_parameters(x_values)

Sys = struct(...
    'S', 1/2, ...
    'g', 2.0023, ...
    'lw', [0.5, 0.5] ...
    );
Exp = struct(...
    'Range', [min(x_values), max(x_values)], ...
    'nPoints', length(x_values), ...
    'mwFreq', 9.67, ...
    'Harmonic', 1 ...
    );
Opt = struct();

end