function [result, fit_results] = eprfit_fitting_function(...
    x_values, y_values, variables, simulation_parameters, fit_parameters, ...
    fit_options)

simulation_function = @(variables, x_values)eprfit_simulation_function(...
    x_values, variables, simulation_parameters);

result = simulation_function(variables, x_values);

plot(x_values, result)

[result, resnorm, residual, exitflag, output, lambda, jacobian] = ...
    lsqcurvefit(simulation_function, variables, x_values, y_values, ...
    fit_parameters.lower_boundaries, fit_parameters.upper_boundaries, ...
    fit_options);

fit_results = struct(...
    'resnorm', resnorm, ...
    'residual', residual, ...
    'exitflag', exitflag, ...
    'output', output, ...
    'lambda', lambda, ...
    'jacobian', jacobian ...
    );

end